### ISSUE TITLE
OU field displays [] when requesting certificates

### ISSUE THREAD

**Issue by jmeldrum76** [Venafi/ansible-role-venafi#16]
**PROBLEM SUMMARY**
OU field displays [] when requesting certificates.
 
![image](https://user-images.githubusercontent.com/21229220/68700787-c63ba700-0542-11ea-9f13-dd4f69e8e369.png)

**STEPS TO REPRODUCE**

1. Install Ansible and vcert using the default instructions from the readme.
2. Create Credentials.yml file
Example:

```
user: 'myuser'
password: 'mypassword'
url: 'https://venafi_server/vedsdk/'
zone: "Demo\\APIs\\Ansible"
trust_bundle: "/home/venafilab/ansible/venafilab_trust_bundle.pem"
```
3. Create Sample.yml

```
---
- hosts: localhost
  roles:
    - role: venafi.ansible_role_venafi
      #certificate_common_name: "{{ ansible_fqdn }}.alex-test.venafi.com"
      certificate_common_name: "testcert2.se.venafi.com"
      certificate_cert_dir: "/tmp/etc/ssl/{{ certificate_common_name }}"
```
4. Run playbook
ansible-playbook sample.yml

**EXPECTED RESULTS**
I would expect an empty OU field due to no policy default

![image](https://user-images.githubusercontent.com/21229220/68701270-a193ff00-0543-11ea-936a-9d14763e35dc.png)

**ACTUAL RESULTS**
![image](https://user-images.githubusercontent.com/21229220/68700787-c63ba700-0542-11ea-9f13-dd4f69e8e369.png)

**ENVIRONMENT DETAILS**
vcert=0.6.8
Ansible=0.2.1
Python=2.7.15+
Ubuntu=18.0.4

**COMMENTS/WORKAROUNDS**
No workaround. I really need to get this fixed. The cannot be use in production with my customer until this is resolved.
